---
deployment:  
  tasks:  
    - export DEPLOYPATH=/home/u3864172/public_html/portofolio  
    - /bin/cp index.html $DEPLOYPATH  
    - /bin/cp -R css $DEPLOYPATH  
    - /bin/cp -R fonts $DEPLOYPATH  
    - /bin/cp -R img $DEPLOYPATH  
    - /bin/cp -R js $DEPLOYPATH  
    - /bin/cp -R source-files $DEPLOYPATH  
    - /bin/cp -R video $DEPLOYPATH  
    - /bin/cp .htaccess $DEPLOYPATH  
    - /bin/cp mail.php $DEPLOYPATH  
    - /bin/cp README.md $DEPLOYPATH